spring.application.name=bookmanagement
server.port=8080
# Database name will be 'university_library'
spring.data.mongodb.uri=mongodb://localhost:27017/university_library
# Ensures ISBN unique index is created
spring.data.mongodb.auto-index-creation=true