spring.application.name=Book-Management

server.port=8080
# Database name is 'university_library'
spring.data.mongodb.uri=mongodb://localhost:27017/university_library
# Ensures @Indexed(unique=true) works for ISBN
spring.data.mongodb.auto-index-creation=true